etherpad:
  image: osones/etherpad:alpine
  volumes:
    - /home/core/pad_osones_com_volume:/etherpad/var
revproxy:
  image: osones/nginx:revproxy-auth
  volumes:
    - /home/core/nginx/certs:/etc/nginx/certs
  links:
    - etherpad:etherpad
  env_file:
    - /home/core/creds.env
  ports:
    - "80:80"
    - "443:443"
